export const philippineBanks = [
    "BDO Unibank",
    "Bank of the Philippine Islands (BPI)",
    "Metropolitan Bank & Trust Company (Metrobank)",
    "Land Bank of the Philippines",
    "Philippine National Bank (PNB)",
    "Development Bank of the Philippines (DBP)",
    "Security Bank",
    "China Banking Corporation (Chinabank)",
    "Union Bank of the Philippines (UnionBank)",
    "Rizal Commercial Banking Corporation (RCBC)",
    "EastWest Bank",
    "Asia United Bank (AUB)",
    "Philippine Bank of Communications (PBCom)",
    "Philippine Veterans Bank",
    "Maybank Philippines",
    "HSBC Philippines",
    "Citibank Philippines",
    "Standard Chartered Bank Philippines",
    "Bank of Commerce",
    "Robinsons Bank",
    "CTBC Bank Philippines",
    "Sterling Bank of Asia",
    "Philippine Savings Bank (PSBank)",
    "Queen City Development Bank",
    "Producers Bank",
    "PNB Savings Bank",
    "Wealth Development Bank",
    "AllBank",
    "Card SME Bank",
    "Dungganon Bank",
    "Malayan Bank Savings and Mortgage Bank",
    "Bangko Mabuhay",
    "BPI Direct Savings Bank",
    "BPI Family Savings Bank",
    "CARD Bank",
    "Citystate Savings Bank",
    "Dungganon Bank",
    "East West Rural Bank",
    "Equicom Savings Bank",
    "Yuanta Savings Bank"
].sort();